version: '3'
services:
  web:
    container_name: "follow-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: postgres_db
      DB_PORT: 5423

  db:
    image: postgres:12.9
    restart: always
    ports:
      - '5424:5423'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=compose-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: false